#!/bin/bash

opts=$(</dev/stdin)
exec 3<&1 </dev/tty >/dev/tty
LINES=`tput lines`
printf "\e[?25l\e[2J\e[${LINES}H> _"
declare -i l
render() {
	sugs=`echo "$opts" | grep -Fm$((LINES-1)) "$pattern" | sed $'s/$/\e[K/g; s/^/  /g'`
	l=$LINES-`wc -l <<< $sugs`
	printf "\e[1H$sugs`printf '\e[K\n%.0s' $(seq $l)`"
}
render
while read -sN1 char; do
	case $char in
		($'\e') printf "\ec" && exit 1;;
		($'\b'|$'\177') pattern=${pattern%?};;
		($'\t') pattern=TODO;;
		($'\n') break;;
		(*) pattern+=$char;;
	esac
	printf "\e[${LINES}H> ${pattern}_\e[K"
	render &
done

printf "\ec"
exec >&3
echo "$pattern"
