#!/bin/bash

print() { printf "$1" >> /dev/tty; }
print "\e[2J\e[5H> "
opts=$(</dev/stdin)

while read -sN1 char; do
	case $char in
		($'\e') print "\ec" && exit 1;;
		($'\b'|$'\177') pattern=${pattern%?};;
		($'\t') pattern=TODO;;
		($'\n') break;;
		(*) pattern+=$char;;
	esac
	print "\e[5H> $pattern"
done </dev/tty

print "\ec"
echo "$pattern"
