#!/bin/bash

opts=$(</dev/stdin)
exec 3<&1 </dev/tty >/dev/tty
print() { printf "$1" >> /dev/tty; }
print "\e[?25l\e[2J\e[6H> _"
LINES=`tput lines`
declare -i l
render() {
	sugs=`echo "$opts" | grep -Fm$((LINES-1)) "$pattern" | sed $'s/$/\e[K/g; s/^/  /g'`
	l=$LINES-`wc -l <<< $sugs`
	print "\e[1H$sugs`printf '\e[K\n%.0s' $(seq $l)`"
}
render
while read -sN1 char; do
	case $char in
		($'\e') print "\ec" && exit 1;;
		($'\b'|$'\177') pattern=${pattern%?};;
		($'\t') pattern=TODO;;
		($'\n') break;;
		(*) pattern+=$char;;
	esac
	print "\e[${LINES}H> ${pattern}█\e[K"
	render &
done </dev/tty

print "\ec"
exec >&3
echo "$pattern"
