#!/bin/bash

opts=$(</dev/stdin) len=$(wc -l <<< $opts) cur=1
exec 3<&1 </dev/tty >/dev/tty
printf "\e[?25l\e[2J\e[?7l"

declare -i cur
render() {
	printf "\e[H"
	sed $'s/$/\e[K/g; s/^/  /g' <<< $opts
	printf "\b \e[${cur}H>"
}

render
while read -sN1 char; do
	case $char in
		(j) cur=$cur%$len+1;;
		(k) cur=($cur+$len-2)%$len+1;;
		(q|h) printf "\ec" && exit 1;;
		(l) break
	esac
	render
done

printf "\ec"
exec >&3
sed -n ${cur}p <<< $opts
